# Welcome to the config file. Please read the README.md file found at the ymls folder.

bot-token: "Your Token Here" # The bot token for your bot.
text-prefix: "b."            # The prefix for text commands. They can be found at the README file mentioned above.

# Stuff that will be shown on /about.
about:
  description: "Collect balls on Discord. Made for people without Docker or PC." # Edits the first line of /about.
  github-link: "https://github.com/wascertified/dockerless-dex"                  # Only change this if you have a fork, this is not required and can be skipped.
  discord-invite: "https://discord.gg/RSdcTAn7FG"                                # Change to your discord server.

# Stuff that will be used on commands.
collectibles-name: "ball"       # Don't add an "s" as the bot will already add the extra "s".
bot-name: "Dockerless-Dex"      # The name of the dex.
players-group-cog-name: "balls" # No spaces, must be lowercase.

# For having multiple, just make sure it matches this look:
#
#authorized-users:
#  - 1234567890
#  - 12345678902
#
# Remember to get the user ID, not the username. You can get them by enabling 'Developer Mode' through settings and right clicking on a username
# and clicking on 'Copy User ID'. On your phone, enable 'Developer Mode' and go to a user profile: Once you're in a user profile just click on
# the three dots in there. Click on 'Copy User ID' and you should be AOK.
### NOTES ON AUTHORIZED USERS: ###
# Only give to people you trust.
# It will also give the user the permission of using the kill command (which turns off the bot).
# With great power comes great responsability.

# Bot startup status configuration.
startup_status:
  activity_type: "watching"                # Options: playing, streaming, listening, watching
  activity_name: "Dockerless-Dex"          # Name of the activity.
  status: "dnd"                            # Options: online, idle, dnd, invisible
  stream_url: "http://twitch.tv/settings"  # Required if activity_type is streaming. If it is a YouTube link, it must be a Stream-type video.
